### ISSUE TITLE
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

### ISSUE THREAD

**Issue by stevemarksd** [graysonhicks/gatsby-plugin-loadable-components-ssr#10]
Somehow I'm getting `Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.` on everything that is rendered... not sure why.

Also this error happens on a component that I didn't even `import` dynamically...

```
  System:
    OS: Windows 10 10.0.19041
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
  Binaries:
    Node: 14.7.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.7 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.8.5
  Browsers:
    Chrome: 87.0.4280.66
    Edge: Spartan (44.19041.423.0), Chromium (87.0.664.52)
  npmPackages:
    gatsby: 2.25.0 => 2.25.0
    gatsby-common: link:../../packages/gatsby-common => 1.0.0
    gatsby-image: 2.4.16 => 2.4.16
    gatsby-plugin-catch-links: ^2.0.9 => 2.3.15
    gatsby-plugin-emotion: ^4.0.0 => 4.5.0
    gatsby-plugin-layout: ^1.3.0 => 1.3.13
    gatsby-plugin-loadable-components-ssr: ^2.1.0 => 2.1.0
    gatsby-plugin-manifest: ^2.0.12 => 2.4.35
    gatsby-plugin-material-ui: ^2.1.8 => 2.1.10
    gatsby-plugin-netlify-cms: ^4.3.17 => 4.3.17
    gatsby-plugin-react-helmet: ^3.0.0 => 3.3.14
    gatsby-plugin-s3: ^0.3.4 => 0.3.8
    gatsby-plugin-sharp: 2.6.24 => 2.6.24
    gatsby-plugin-sitemap: ^2.0.3 => 2.4.17
    gatsby-plugin-typescript: ^2.0.3 => 2.4.24
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.9 => 1.1.13
    gatsby-react-router-scroll: ^3.0.12 => 3.0.15
    gatsby-remark-component: ^1.1.3 => 1.1.3
    gatsby-remark-images: ^3.0.1 => 3.3.39
    gatsby-remark-relative-images: ^2.0.2 => 2.0.2
    gatsby-source-filesystem: ^2.3.23 => 2.3.37
    gatsby-transformer-remark: ^2.1.15 => 2.8.46
    gatsby-transformer-sharp: 2.5.12 => 2.5.12


```

![image](https://user-images.githubusercontent.com/58653359/101075000-6b0ca480-35dc-11eb-8676-260258234c7e.png)

The encoded error is: `Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined`

I tried to put at the bottom or top of the plugin list, same error. **Even if I remove it from the plugins, still same error.** 

Seems like the issue is that the plugin is not even loaded...

If I change some files error changes location:

![image](https://user-images.githubusercontent.com/58653359/101076182-f8042d80-35dd-11eb-972e-9c8e5719d84f.png)

**Comment by graysonhicks** [comment]
@stevemarksd This is normally caused by mixed up import syntax, especially named vs. default.  Are you still having this issue and/or have a reproduction?  Thanks!
