### ISSUE TITLE
Increased LCP with beta plug-in

### ISSUE THREAD

**Issue by afladmark** [graysonhicks/gatsby-plugin-loadable-components-ssr#19]
We rolled out the latest beta to our website this afternoon and pretty immediately noticed a >2x degradation of our LCP numbers. I've tried to profile it and see if I could spot why, but I'm not sure I'm any closer.

It looks like LCP has moved until after React has loaded and loadable components have been fired (previously our initial load, FCP and LCP were all the same instant earlier than that). Visually, we have a video on our homepage and we can see it jump and restart from the beginning around the time now identified as LCP.

My initial thought is that it's rendering rather than hydrating or something, but I couldn't see any issues with the code. One of the only major differences between what we did as part of a local update to support Gatsby 3 and what's in the plugin is that we have a radically simplified replaceHydrateFunction as we use dev SSR mode:

```
export const replaceHydrateFunction = () => (element, container, callback) => {
  loadableReady(() => {
    hydrate(element, container, callback)
  })
}
```

It might be something else, of course.

I've had to revert it off the site atm as we're really performance sensitive, but I'm happy to try and help repro and potentially try to spot a fix as well over the next couple of days but would be grateful for any ideas.

We're really keen to get back onto the plugin if possible and are so glad to see it come back to being maintained.

Thank you for your work on it.

Andrew

**Comment by graysonhicks** [comment]
@afladmark So is your replaceHydrate function replacing the one that loadable uses in this plugin?

**Comment by afladmark** [comment]
@graysonhicks So, for a bit more context, when I created #13 as an attempt at Gatsby 3 support, I ran into an issue where it worked everywhere except for the Gatsby Cloud builds. For reasons I assume relate to resolving the path to the public folder, I never got any SSR output when building in Gatsby Cloud. 

As a workaround, and as I laid out here https://github.com/graysonhicks/gatsby-plugin-loadable-components-ssr/issues/12#issuecomment-811117554, I ended up implementing the code directly in our Gatsby project, rather than using a plug-in as it didn't appear at the time this plug-in would ever be updated.

So the difference we see in LCP is comparing that direct code implementation we're currently running within our project to the implementation in the beta version of this plugin. I've checked we're on the same versions of loadable-components itself and most of the code is effectively identical, but the obvious exception was the simplified `replaceHydrate` function. Not sure if it's actually the issue though.

**Comment by graysonhicks** [comment]
Thanks for that @afladmark, and yes, some comparison sites would be great to look at, thanks!

**Comment by graysonhicks** [comment]
Also, as this is `next` related, just noting that I released `3.0.0` today. 👍

**Comment by graysonhicks** [comment]
@afladmark Have you been able to confirm this or see if it is still an issue in `3.2.0`?

**Comment by afladmark** [comment]
I'll test it tomorrow on latest version of Gatsby and of this component. If I can see the LCP difference clearly on a Gatsby Cloud branch build (vs the equivalent main branch build) I'll let you know.

**Comment by afladmark** [comment]
@graysonhicks I have good news to report here. We've integrated version `3.3.0` of the plugin and have seen no recurrance of the issue we previously reported with increased LCP. It's been running on our production site for most of the day and everything looks exactly as expected, so I think we're good to close this issue. Thank you so much for your work on this!

**Comment by graysonhicks** [comment]
Thanks @afladmark !
