### ISSUE TITLE
WebpackError: Unsafe builtin usage fs.existsSync

### ISSUE THREAD

**Issue by rinorzek** [graysonhicks/gatsby-plugin-loadable-components-ssr#23]
I recently updated all the dependencies of my projects along with gatsby v3.6.1 and when I'm trying to build the project it's throwing an warning saying `WebpackError: Unsafe builtin usage fs.existsSync` and it's pointing at the gatsby-plugin-loadable-components-ssr/gatsby-ssr.js file. I think that is because of the usage of fs instead of import now with the latest gatsby update as they mention that [here](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/#using-fs-in-ssr). So is there any updates on that or maybe I'm missing something. :)

**Comment by graysonhicks** [comment]
Hi @rinorzek what version of `gatsby-plugin-loadable-components-ssr` are you using?

**Comment by rinorzek** [comment]
@graysonhicks I'm using v2.1.0

**Comment by graysonhicks** [comment]
You should upgrade the plugin to `3.0.0`

**Comment by rinorzek** [comment]
@graysonhicks great thanks! thought I had the latest version but saw that that version is the latest for gatsby 2 👍🏼
