### ISSUE TITLE
Plugin includes react-dom in bundle, causing duplicate in Gatsby build output.

### ISSUE THREAD

**Issue by justinluttrell** [graysonhicks/gatsby-plugin-loadable-components-ssr#26]
I recently noticed that sites using this plugin have `react-dom.production.min.js` show up twice in the build output. Once in the Gatsby framework bundle and once in the gatsby-plugin-loadable-components-ssr bundle. 

Lighthouse highlights this as an opportunity for improvement.

![image](https://user-images.githubusercontent.com/51456668/122099736-58bbc080-cde0-11eb-91bf-241e46561703.png)

  
  

Using [gatsby-plugin-webpack-bundle-analyser-v2](https://www.gatsbyjs.com/plugins/gatsby-plugin-webpack-bundle-analyser-v2/) to analyze the bundles, you can see both instances.

![image](https://user-images.githubusercontent.com/51456668/122099935-9587b780-cde0-11eb-9c9d-0185c269577e.png)

Is including this in the output bundle required? Or is there a way to configure the plugin to not include it?

**Comment by graysonhicks** [comment]
Looks like a bug.  Thanks, I'll look in to this!

**Comment by graysonhicks** [comment]
@justinluttrell Can you verify which versions you are using?

**Comment by justinluttrell** [comment]
v2.1.0

**Comment by justinluttrell** [comment]
Updating to v3.0.0 fixes the issue.


![image](https://user-images.githubusercontent.com/51456668/122114077-df789980-cdf0-11eb-9dc8-c5db920eb464.png)
