### ISSUE TITLE
[Question] How to use it properly

### ISSUE THREAD

**Issue by Kikobeats** [graysonhicks/gatsby-plugin-loadable-components-ssr#28]
Hey hello,

I recently discovered `loadable-components` and I have fallen in love.

However, I have a question pending: is this really necessary in a Gatsby project?

When I do a build of my Gatsby project, I can see JS chunks are actually split into smaller chunks.

I guess this library is replacing the original Gatsby behavior and do the same but the job to `loadable-components`?

**Comment by graysonhicks** [comment]
Hi @Kikobeats I actually have a blog post that will explain this in a lot of detail going out in the next week or so.  I will paste the link here and close this when it is published.  Thanks!

**Comment by vivacoda** [comment]
> Hi @Kikobeats I actually have a blog post that will explain this in a lot of detail going out in the next week or so. I will paste the link here and close this when it is published. Thanks!

Thanks I am interested also for properly setup and use it with gatbsy-link.
Best regards

**Comment by ashleynexvelsolutions** [comment]
I'm also looking forward to reading the blog post. Thanks @graysonhicks

**Comment by graysonhicks** [comment]
Blog post with some more reasoning is up here, thanks!

https://www.gatsbyjs.com/blog/flexible-fine-grained-code-splitting-with-gatsby-loadable-components
