### ISSUE TITLE
Error: loadable-components: failed to asynchronously load component,[object Object]

### ISSUE THREAD

**Issue by nestarz** [graysonhicks/gatsby-plugin-loadable-components-ssr#30]
Hello !

I use this plugin at version 3.2.0 with a Gatsby 3.8.0 project but have 3-4% users that triggers the following error:

`loadable-components: failed to asynchronously load component,[object Object]
`
It does't happens with the version 2.2.1-beta.2 on Gatsby 3.6.1.

Tell me if you need more information. 

Best,

**Comment by graysonhicks** [comment]
Hi!  Thanks for bringing this up.  Yes, can you post some more information on the environment where you are seeing this?  Thanks!
