### ISSUE TITLE
Cannot find chunk in stats in dev-ssr mode

### ISSUE THREAD

**Issue by Leksat** [graysonhicks/gatsby-plugin-loadable-components-ssr#33]
For example, you have two pages:
- a page that uses loadable (loadable-page)
- a page which does not use loadable but links to the loadable-page (regular-page)

Success scenario:
- run `gatsby clean && gatsby develop`
- go to the regular-page url
- hover over the loadable-page link (this is the key to make it success, but I don't know why)
- go to the loadable-page url => it works

Failure scenario:
- run `gatsby clean && gatsby develop`
- go to the loadable-page url directly => it does not work

The error is
```
Invariant Violation: loadable: cannot find my-loadable-component in stats (from plugin: gatsby-plugin-loadable-components-ssr)
```
(actually you might see `Cannot read property 'split' of undefined` instead, because of a bug in gatsby's error handling)

**Comment by Leksat** [comment]
> hover over the loadable-page link (this is the key to make it success, but I don't know why)

The hover generates the json file for the target page in `/.cache/json` directory. But I don't know how this affects webpack/loadable.

**Comment by graysonhicks** [comment]
Hi @Leksat thanks for the report.  I was unable to reproduce using this test site I use.  Do you mind trying to make a minimal reproduction?  (The test site is using 3.3.0).

https://github.com/graysonhicks/loadable-test

**Comment by Leksat** [comment]
🤔 I'll try.

**Comment by Leksat** [comment]
Hmm, I also can't reproduce it on the test repo. Closing for now.
