### ISSUE TITLE
Error: loadable-components: failed to synchronously load component, which expected to be available

### ISSUE THREAD

**Issue by julrich** [graysonhicks/gatsby-plugin-loadable-components-ssr#38]
When running in development, everything works as expected, and the generated chunks (per component) are loaded perfectly fine.

When trying to generate a production build, though, I'm being greeted by the following errors:
```
loadable-components: failed to synchronously load component, which expected to be available {
  fileName: null,
  chunkName: 'kickstartds-blog-lib-post-teaser-index-js',
  error: "Cannot read property 'call' of undefined"
}
```

```
loadable-components: failed to synchronously load component, which expected to be available {
  fileName: null,
  chunkName: 'kickstartds-base-lib-text-media-index-js',
  error: 'resolveComponent returned something that is not a React component!'
}
```

```
ERROR #95313

Building static HTML failed for path "/blog"

See our docs page for more info on this error: https://gatsby.dev/debug-html


  17 |
  18 |  // Execute the module function
> 19 |  __webpack_modules__[moduleId].call(module.exports, module, module.exports, __webpack_require__);
     | ^
  20 |
  21 |  // Flag the module as loaded
  22 |  module.loaded = true;


  WebpackError: TypeError: Cannot read property 'call' of undefined

  - bootstrap:19
    @kickstartds/website/webpack/bootstrap:19:1

  - PageComponent.tsx:27
    [website]/[@kickstartds]/gatsby-theme-kickstartds/src/components/PageComponent.tsx:27:31

  - loadable.esm.js:278
    [website]/[@loadable]/component/dist/loadable.esm.js:278:1

  - loadable.esm.js:173
    [website]/[@loadable]/component/dist/loadable.esm.js:173:1
```

Maybe of note, we are using dynamic import paths in our template page component... where components can vary per page instance, according to the CMS data ingested. Like this (where `value[0]` holds the name of the component to import):
```
    components[key] = loadable(() => import(`@kickstartds/base/lib/${key}/index.js`), {
      resolveComponent: (exports) => exports[value[0]],
    });
```

Could this necessitate additional setup steps to get the production build to run through?

Those two issues definitely seem related:
* https://github.com/graysonhicks/gatsby-plugin-loadable-components-ssr/issues/6
* https://github.com/graysonhicks/gatsby-plugin-loadable-components-ssr/issues/4

Edit: This one, too: https://github.com/gregberge/loadable-components/issues/621

Unfortunately it's still not really clear to me as to what's happening.

Tried to add some more context, as to what we're trying to do in a gist. With a more complete sample of the page template we're trying to build:
https://gist.github.com/julrich/73441d0f94fcc581b29183168060d2c9

Also rewrote the `loadable()`-calls a bit, but the error stays the same.

**Comment by julrich** [comment]
Those two issues definitely seem related:
* https://github.com/graysonhicks/gatsby-plugin-loadable-components-ssr/issues/6
* https://github.com/graysonhicks/gatsby-plugin-loadable-components-ssr/issues/4

**Comment by julrich** [comment]
Tried to add some more context, as to what we're trying to do in a gist. With a more complete sample of the page template we're trying to build:
https://gist.github.com/julrich/73441d0f94fcc581b29183168060d2c9

**Comment by lmestel** [comment]
Here is a minimal setup to reproduce this: https://github.com/lmestel/gatsby-loadable-component-demo

With `import("../components/list-item")` everthing works as expected, but with ``import(`../components/${props.component}`)`` (and later `<Component component="list-item" … />`), i get the same error as @julrich on production build.

**Comment by graysonhicks** [comment]
Hi @julrich and @lmestel , yes there is definitely an issue with fully dynamic imports and this plugin.  The [main workaround is making a 'map' component](https://github.com/graysonhicks/gatsby-plugin-loadable-components-ssr/issues/4#issuecomment-684814893).  I am sure there is a solution, likely in the stats map that is being generated, but I don't know if I will have time to implement it, and the hope of deprecating this plugin in favor of React.lazy soon 😄 .  Definitely open to adding support for it, but currently more as a feature request than a bug.

**Comment by julrich** [comment]
@KyleAMathews I think so, yes. I've found 2 or 3 such cases in the tickets, but all paths were ultimately leading here, in the end:
https://github.com/gregberge/loadable-components/issues/621#issuecomment-687530179

Which still seems to be the current state of affairs :)

Maybe a note in the readme would even be enough. It's just not very clear that there are limitations, currently, as articles as the following sort of suggest that this could / should work, and is suggested as a solution:
https://www.gatsbyjs.com/blog/flexible-fine-grained-code-splitting-with-gatsby-loadable-components/

@graysonhicks Thanks for clarifying. Was suspecting that :) We've already, in the meantime, pretty much implemented exactly that approach (stumbled upon that comment, too). We'll happily join in waiting for `React.lazy`, then, too ;).

Not sure if the code is useful for someone else, because we're reading all available components from an `exports.json` file (per component package), which is generated during publishing time of those frontend packages, but you never know:
https://gist.github.com/julrich/f43c04d95d82573181d7f29dfe077024

**Comment by graysonhicks** [comment]
Thanks for the extra information @julrich and yes, I will definitely add something in the docs noting that dynamic imports do not have first-class support!

**Comment by julrich** [comment]
For everyone stumbling upon this after the fact: This is a great introductory talk by Grayson about those coming `React.lazy` changes in React 18

https://www.youtube.com/watch?v=lypEGNEIRKE
