### ISSUE TITLE
Import component dynamically. WebpackError: TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by nkosakul** [graysonhicks/gatsby-plugin-loadable-components-ssr#4]
Hi!

First, thanks for the plugin! Really cool!

I´m using `@loadable/component` for a portfolio website with Gatsby + Contentful.
Its working great with Gatsby version `2.20.36`, but as soon as i update Gatsby to `2.20.4` or higher, which i do because of the incremental build feature i want to use, its failed on build.

I´m using `gatsby-plugin-loadable-components-ssr` `v2.0.0`

The Error i get is `WebpackError: TypeError: Cannot read property 'call' of undefined`.
The Error comes up, while gatsby is building the html pages

My Code:
```js
import loadable from '@loadable/component';

...


page.elements.map((element) => {
  const typename = element.__typename.replace('Contentful', '');
  const Component = loadable(() =>
    import(`../components/${typename}`)
  );
  
  return <Component props={element} key={element.id} />;
})}
```

gatsby-config.js looks like this
```js
{
      resolve: `gatsby-plugin-loadable-components-ssr`,
      options: {
        // Whether replaceHydrateFunction should call ReactDOM.hydrate or ReactDOM.render
        // Defaults to ReactDOM.render on develop and ReactDOM.hydrate on build
        useHydrate: true,
      },
    },
```

I´m new to gatsby and its my first time using it with contentful, so sorry if its a dumb question.

Here is also the link to my repo
https://github.com/nkosakul/pepita/tree/develop

**Comment by nkosakul** [comment]
A Screenshot from the console:
<img width="818" alt="Bildschirmfoto 2020-05-13 um 19 15 40" src="https://user-images.githubusercontent.com/28593228/81843643-2fca5b80-954e-11ea-8606-f47c24c01095.png">

**Comment by hector-del-rio** [comment]
The link you posted to your repo cannot be build because it uses data from Contentful. It is hard to tell what could be going on without a minimal repo to reproduce the error.

**Comment by nkosakul** [comment]
oh sorry, you're right.
you can't build without an .env with the API keys..
would it help if I generate an temporary API key and DM it to you, so you can build the files?

**Comment by hector-del-rio** [comment]
Maybe it's best if you switch to JSON data source in a different branch.

**Comment by nkosakul** [comment]
Ok, so i created a new branch `source-json` where i´m sourcing the data from a json file, instead of contentful. I made the branch as simply as i could and build the data similiar to the contentful response.
I get rid of all the other pages, so the index.js is now the only page which is being created.

on `yarn start` everything works great. On build its throw out the same error above.

Here is the link:
https://github.com/nkosakul/pepita/tree/source-json

Thanks for your time, i  appreciate it  🙏🏻

**Comment by hector-del-rio** [comment]
I spent almost the whole day yesterday trying to figure out what the problem is. I tried debugging gatsby's build process. There seems to be some problem with how the modules are loaded, but I can't figure out exactly what.

It would be really helpful to find what version of gatsby was still working, but when I tried `2.20.36` as you mentioned, it didn't work either. Could you let me know if you find a version that works?

**Comment by nkosakul** [comment]
Ok, thats weard.. now it doesn´t work for me either.
I also throw everything out except for the files, that we really need (pushed to source-json branch).
I even created a whole new repo on a different machine and it doesn´t work too..

I did some testing, maybe its helping:
On develop, if i go back to the commit, before i bump up gatsby, its still working.
So i just copied the yarn.lock file (i know, i shouldn´t) from there and push it to develop.
And see there.. build is running fine again.
But (of course), if i let yarn re-create the lock file.. build its failing again.

(The file, where everything works fine: https://github.com/nkosakul/pepita/blob/test/yarn.lock)

I´m super confused

**Comment by hector-del-rio** [comment]
Ok, that `yarn.lock` was usefull 👍

Adding the resolution below in `packaga.json` will fix the issue for now

```
"resolutions": {
    "@babel/core": "7.8.4"
  }
```

Now I only need to figure out what has changed between the two version of babel.

**Comment by nkosakul** [comment]
I´m glad that helped! And thank you!

This fix seems to fail at the first build, when there is no `.cache` folder,
but every other build after the first build is running clean.
(With: gatsby `2.20.4`, gatsby-plugin-loadable-components-ssr `^2.1.0` and with `resolutions` added to the `package.json`)

So for me, netlify will still fail to deploy.
So i might gonna wait for now. 🤔

**Comment by MastaAaron** [comment]
Any hope for getting this resolved? I'm also experiencing the error...

**Versions installed:**
`gatsby@2.24.8`
`@loadable/component@5.13.1`
`gatsby-plugin-loadable-components-ssr@2.1.0`
`@babel/core@7.8.4` (via `"resolutions"` entry in `package.json`)

**Comment by StrategyLLC** [comment]
We are getting this same error. We are using WordPress as our data source, but the code looks exactly the same as what was posted. Using latest versions. Anybody have any insight to this issue outside of what has already been posted?

**Comment by ashhitch** [comment]
Same for me. I tried taking a fork of the repo and updating the dependencies but it did not help. (was hoping for an easy win!)

**Comment by SimeonC** [comment]
Looks like this issue in the main repo is related; https://github.com/gregberge/loadable-components/issues/599

The only way I managed to get around this was by removing the dynamic imports - basically, instead of passing the component name/path as a string I write the whole `loadable(() => import` and pass that instead.

**Comment by MaxBoltik** [comment]
any news?

**Comment by MaxBoltik** [comment]
> Looks like this issue in the main repo is related; [gregberge/loadable-components#599](https://github.com/gregberge/loadable-components/issues/599)
> 
> The only way I managed to get around this was by removing the dynamic imports - basically, instead of passing the component name/path as a string I write the whole `loadable(() => import` and pass that instead.

Could you please explain a bit more about  "I write the whole loadable(() => import and pass that instead."

**Comment by SimeonC** [comment]
So instead of `<DynamicLoader file=“filename”>` I ended up writing something like `<DynamicLoader loadable={loadable(() => import(‘path/to/filename’)}>`

Don’t know how helpful that would be for you, it’s not as clean as what we’d like but it works. Basically you hardcode the loadable components and dynamically select them instead of using a dynamic import.

**Comment by MaxBoltik** [comment]
I've found another workaround.

Wrapper for dynamic component like this:
```javascript
import React from 'react';
import loadable from '@loadable/component';

const ProxyComponent = (props) => {
  const Loaded = loadable(() => import('./Component'));

  return <Loaded {...props} />;
}

export default ProxyComponent
```
A map for component list:
```javascript
import ProxyComponent from './ProxyComponent';
//...other imports

export default {
  'ProxyComponent': ProxyComponent,
  //...other components
};

```  
And eventually use this map where I need this dynamic component:
```javascript
const componentName = 'ProxyComponent';
const SomeDynamicComponent = proxyMap[componentName];

  return (
    ...
      <SomeDynamicComponent />
    ...
  );
``` 
It works in SSR as a static and in SPA as a dynamic.

**Comment by abahari** [comment]
Hello Everyone, 

I solved this problem by adding the following condition: 
```
let DynamicModule = null;
const windowGlobal = typeof window !== 'undefined' && window;
  if (windowGlobal){
    DynamicModule = loadable((props) => import(`../components/${props.module}`));
  }
```
and before calling this module, check if it DynamicModule exists : 
```
{
   DynamicModule && <DynamicModule module={`your module name`} />
}
```

I hope this help

**Comment by alesanchezr** [comment]
Same issue here, I'm only loading icons so for now I'm just ignoring the icons during SSR

```jsx
import React, { useEffect } from 'react';
import loadable from '@loadable/component'
import PropTypes from 'prop-types';

const Icon = ({ icon, ...rest }) => {
    if(typeof(window) === 'undefined' || !window) return "";

    const Comp = loadable(() => import(`./set/${icon}`))
    return <Comp {...rest} />
}
Icon.propTypes = {
    icon: PropTypes.string.isRequired,
    color: PropTypes.string.isRequired,
}
export default Icon;
```

**Comment by lunelson** [comment]
I'm getting the same error here with `gatsby 2.28.2` and this plugin `2.1.0`. I'm also using the pathPrefix option, which might be relevant. The solution of using the `resolutions` field in `package.json`, as mentioned further up this thread, didn't work for me.
