### ISSUE TITLE
Gatsby v4.1.0 throws "Generated engines use disallowed import" error due to stats JSON import

### ISSUE THREAD

**Issue by LiamMartens** [graysonhicks/gatsby-plugin-loadable-components-ssr#45]
![image](https://user-images.githubusercontent.com/5265324/140087667-331e2ca3-e7e9-4b30-bb25-772685a11770.png)

`Error: Generated engines use disallowed import "/workspaces/heights-gatsby/.cache/loadable-stats-build-javascript.json". Only allowed imports are to Node.js builtin modules or engines internals.`

**Comment by laneparton** [comment]
Here's more context, if it is helpful.

`success Building production JavaScript and CSS bundles - 55.276s
⠋ Building Rendering Engines
success Building Rendering Engines - 34.037s
success Building HTML renderer - 35.437s
success Execute page configs - 0.059s
failed Validating Rendering Engines - 1.650s

 ERROR #98001  WEBPACK

Built Rendering Engines failed validation failed validation.

Please open an issue with a reproduction at https://github.com/gatsbyjs/gatsby/issues/new for more help



  Error: Generated engines use disallowed import "/Users/lp234/Projects/GitLab/sitespro-gatsby-base/.cache/loadable-stats-build-javascript.jso
  n". Only allowed imports are to Node.js builtin modules or engines internals.

  - child.ts:60 Function._module.default._load
    [sitespro-gatsby-base]/[gatsby]/src/utils/validate-engines/child.ts:60:11

  - loader:1005 Module.require
    node:internal/modules/cjs/loader:1005:19

  - helpers:94 require
    node:internal/modules/cjs/helpers:94:18

  - util.js:40 smartRequire
    [sitespro-gatsby-base]/[@loadable]/server/lib/util.js:40:12

  - ChunkExtractor.js:204 new ChunkExtractor
    [sitespro-gatsby-base]/[@loadable]/server/lib/ChunkExtractor.js:204:1

  - gatsby-ssr.js:12 Object.6772
    [sitespro-gatsby-base]/[gatsby-plugin-loadable-components-ssr]/gatsby-ssr.js:12:19

  - bootstrap:19 require
    /Users/lp234/Projects/GitLab/sitespro-gatsby-base/.cache/page-ssr/routes/webpack:/@dws-contributes/sitespro-gatsby-base/webpack/bootstrap:
    19:1

  - api-runner-ssr.js:3 Module.9874
    /Users/lp234/Projects/GitLab/sitespro-gatsby-base/.cache/page-ssr/routes/webpack:/@dws-contributes/sitespro-gatsby-base/.cache/api-runner-
    ssr.js:3:15

  - bootstrap:19 require
    /Users/lp234/Projects/GitLab/sitespro-gatsby-base/.cache/page-ssr/routes/webpack:/@dws-contributes/sitespro-gatsby-base/webpack/bootstrap:
    19:1

  - static-entry.js:15 Module.3451
    /Users/lp234/Projects/GitLab/sitespro-gatsby-base/.cache/page-ssr/routes/webpack:/@dws-contributes/sitespro-gatsby-base/.cache/static-entr
    y.js:15:39

  - bootstrap:19 __webpack_require__
    /Users/lp234/Projects/GitLab/sitespro-gatsby-base/.cache/page-ssr/routes/webpack:/@dws-contributes/sitespro-gatsby-base/webpack/bootstrap:
    19:1

  - startup:4
    /Users/lp234/Projects/GitLab/sitespro-gatsby-base/.cache/page-ssr/routes/webpack:/@dws-contributes/sitespro-gatsby-base/webpack/startup:4:
    1

  - render-page.js:13193 Object.<anonymous>
    /Users/lp234/Projects/GitLab/sitespro-gatsby-base/.cache/page-ssr/routes/render-page.js:13193:12

  - loader:1101 Module._compile
    node:internal/modules/cjs/loader:1101:14

  - loader:1153 Object.Module._extensions..js
    node:internal/modules/cjs/loader:1153:10

  - loader:981 Module.load
    node:internal/modules/cjs/loader:981:32`

**Comment by qinyiyao** [comment]
Reproduction: https://codesandbox.io/s/bug-report-gatsby-loadable-plyr-t577j
Error on `yarn build`.

**Comment by graysonhicks** [comment]
Thanks, will be looking at this next week.  Long term, once React 18 is stable, I won't be updating this for further v4 compatibility in place of React.lazy.

**Comment by graysonhicks** [comment]
Fix released in 4.1.0.  Thanks all!
