### ISSUE TITLE
Bug: ENOENT for "page-ssr/loadable-stats-build-javascript.json" file on gatsby build

### ISSUE THREAD

**Issue by Nikhil-Ladha** [graysonhicks/gatsby-plugin-loadable-components-ssr#52]
**Issue:** 
After adding the plugin to the gatsby site, getting the below error while running the `gatsby build` command.

```
ERROR #98123  WEBPACK

Generating JavaScript bundles failed

ENOENT: no such file or directory, open '/home/nladha/layer5/.cache/page-ssr/loadable-stats-build-javascript.json'
```

**Steps to reproduce:**
1. Add the plugin to your site by following the guide mentioned in the README/Gatsby plugin docs
2. Try running `gatsby build`.

**NOTE:**
The issue is not happening while executing `gatsby develop`. I think that's because it is simply ignored in the case of `development` build as per the latest update.

**Comment by debo19** [comment]
I'm facing this same issue on running `gatsby build`.

**Comment by graysonhicks** [comment]
Can you please post a link to the repo with the reproduction?

**Comment by wmt-php-mudramk** [comment]
@graysonhicks 
Is there any update?

@Nikhil-Ladha 
Have you found any workaround?

I am also facing the same issue.

**Comment by kashyapm-wmt** [comment]
@graysonhicks Facing a similar issue with `gatsby build`. Working fine with `gatsby develop`

If you can guide me I can help you to fix this.

Thanks

**Comment by graysonhicks** [comment]
I can't give any update without reproductions of the bug 😄

**Comment by graysonhicks** [comment]
@kashyapm-wmt Can you please post a reproduction?  I was testing yesterday and am unable to replicate.

**Comment by Nikhil-Ladha** [comment]
Hi @graysonhicks , check out this repo (branch: `gatsby-ssr-plugin-bug`) https://github.com/Nikhil-Ladha/layer5/tree/gatsby-ssr-plugin-bug. I have added the plugin, and on doing a gatsby build it is failing.

**Comment by graysonhicks** [comment]
@Nikhil-Ladha You are on Gatsby 3, can you try the plugin version 3.4.0?

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha You are on Gatsby 3, can you try the plugin version 3.4.0?

But, why should I roll back to previous gatsby versions? If not today, then sometime we will move to Gatsby 4, and even then we won't be able to use the `ssr-plugin`.

**Comment by graysonhicks** [comment]
@Nikhil-Ladha Because `3.4.0` is the last version that supports Gatsby v3.  When you move to v4 of Gatsby you can bump this plugin version as well.

**Comment by Nikhil-Ladha** [comment]
Oh ok, got it.
I kind of misunderstood your previous comment, reason being the gatsby release only shows 2.1.0 as the latest 😅
