### ISSUE TITLE
Support for react-dom^18.2.0

### ISSUE THREAD

**Issue by NotFrancee** [graysonhicks/gatsby-plugin-loadable-components-ssr#55]
I'm trying to install this package on my gatsby website, but npm cannot resolve the dependencies. 

Here's the error message: 

> ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: the-daily-bond@1.0.0
npm ERR! Found: react-dom@18.2.0
npm ERR! node_modules/react-dom
npm ERR!   react-dom@"^18.2.0" from the root project
npm ERR!   peer react-dom@"^16.9.0 || ^17.0.0 || ^18.0.0" from gatsby@4.18.2
npm ERR!   node_modules/gatsby
npm ERR!     gatsby@"^4.18.2" from the root project
npm ERR!     peer gatsby@"^2.12.1 || ^3.0.0 || ^4.0.0" from gatsby-plugin-loadable-components-ssr@4.2.0
npm ERR!     node_modules/gatsby-plugin-loadable-components-ssr
npm ERR!       gatsby-plugin-loadable-components-ssr@"*" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-dom@"^16.12.0 || ^17.0.1" from gatsby-plugin-loadable-components-ssr@4.2.0
npm ERR! node_modules/gatsby-plugin-loadable-components-ssr
npm ERR!   gatsby-plugin-loadable-components-ssr@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/andreafranceschini/.npm/eresolve-report.txt for a full report.

**Comment by graysonhicks** [comment]
Hi @NotFrancee !  Can you please post a reproduction?

**Comment by graysonhicks** [comment]
@NotFrancee This is resolved in 4.2.1.  Was a peer deps package.json issue.  Thanks!
