### ISSUE TITLE
Support for React 18

### ISSUE THREAD

**Issue by edward-simpson** [graysonhicks/gatsby-plugin-loadable-components-ssr#57]
Because this plugin uses `reactDom.render` in it's gatsby-browser.js, it prevents using react 18 features:

``` 
Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot
```

**Comment by lezan** [comment]
I am experience the same warning. I tried to check all the libraries used and this one appears to have to do with it.

**Comment by graysonhicks** [comment]
Thanks both!  I'll look at the best way to switch the render method.  One option is releasing a new major version of this plugin to align with [Gatsby v5](https://github.com/gatsbyjs/gatsby/discussions/36609), which will have React 18 as a requirement.

**Comment by graysonhicks** [comment]
I am afraid this is an upstream problem with loadable: https://github.com/gregberge/loadable-components/issues/718

I recommend migrating to `React.lazy` for code-splitting + SSR with React 18.

**Comment by graysonhicks** [comment]
I have removed the React 18 allowance from peer deps in `4.3.0` until this is resolved, but I am not really motivated to push React 18 support for this plugin, when React will now have an official solution baked in.

**Comment by lezan** [comment]
@graysonhicks I did the migration to React.lazy and Suspense, but I am not able to run it (getting this one https://github.com/gatsbyjs/gatsby/issues/36678). Not sure it is a solution supported by Gatbsy.

**Comment by graysonhicks** [comment]
Thanks @lezan but it is supported by Gatsby (despite the apparent bug).

**Comment by lezan** [comment]
Hey @graysonhicks sorry to bother. Does it means is not a bug but I am doing something wrong?

**Comment by graysonhicks** [comment]
No worries @lezan it may be a bug, or it may be user error.  I've responded to your issue on the Gatsby repo and we can track there.  Regardless, this plugin will not support React 18, as Gatsby v5 will with `React.lazy`.
